### ISSUE TITLE
graceful error handling when more than one occurance of same policy name in same file

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1601] opened 2017-09-25 19:25 UTC
Scenario:  two or more policies in the same file have the same name.  Frequently occurs when user cuts-n-pastes within same file to create a new policy but forgets to change the name.

Current Behavior: Custodian outputs: IndexError: list index out of range

Expected Behavior: Custodian outputs: "Duplication policy name detected on line xxx with prior one on line zzz

**Comment by kapilt** [comment] 2017-09-26 12:31
hmm.. this used to be the behavior, seems like a regression. @scotwk ?

**Comment by salwandhruvdev** [comment] 2017-09-26 14:21
@FireballDWF If you do a `custodian validate` before `dryrun`, you will see the following error:
```
custodian validate -c test.yaml 
custodian.commands:ERROR Configuration invalid: another.yaml
custodian.commands:ERROR Only one policy with a given name allowed, duplicates: test-policy
```

**Comment by scotwk** [comment] 2017-09-27 12:59
I'll try to fix today.

**Comment by ewbankkit** [comment] 2017-09-28 13:28
Different code paths when logging the error:
* [`validate`](https://github.com/capitalone/cloud-custodian/blob/master/c7n/commands.py#L193-L195)
* [`run`](https://github.com/capitalone/cloud-custodian/blob/master/c7n/commands.py#L193-L195) - Assumes a second element in the list, the policy that failed to validate

**Comment by scotwk** [comment] 2017-09-28 17:37
@ewbankkit - yes.  I feel like the `run` subcommand should use the same code path as `validate` before doing the run.  I think I looked into combining them months ago and found there were some hurdles.  How much effort is it worth?

**Comment by ewbankkit** [comment] 2017-09-29 01:29
I'd say not worth it right now 😄.

**Comment by ewbankkit** [comment] 2017-09-29 01:43
Closed via https://github.com/capitalone/cloud-custodian/pull/1610.

**Closed by ewbankkit** 2017-09-29 01:43 UTC

**Comment by kapilt** [comment] 2017-10-01 12:08
as noted on the merged pull request, its rather unclear how this fixes the referenced issue, its just adding handling to the extant `happy` path that was already catching this issue, rather then extending it to handle the issue reference issue, the merge and commit there seems rather unlikely that it would actually help anything since its just making the error message less informative afaict (only showing the first of any dupes in err message). @ewbankkit how was that supposed to resolve this issue?

**Comment by kapilt** [comment] 2017-10-01 12:35
ah. its more clear now to me why the referenced fix works, the error protocol in policy load is expecting a tuple of (error, policy_name) which this corrects the dupe detection to use correctly.
