### ISSUE TITLE
OffHours Policy Error

### ISSUE THREAD

**Issue by chaosdarky** [capitalone/cloud-custodian#1922] opened 2018-01-08 11:34 UTC
Hi, I am having an issue in running the offhours policy. Can someone help or guide me to fix this?

> 2018-01-08 10:54:11,967: custodian.commands:ERROR Configuration invalid: offhours.yml
2018-01-08 10:54:11,969: custodian.commands:ERROR Additional properties are not allowed ('onhour' was unexpected)

>Failed validating u'additionalProperties' in schema[12]:
    {u'additionalProperties': False,
     u'properties': {u'default_tz': {u'type': u'string'},
                     'offhour': {u'maximum': 23,
                                 u'minimum': 0,
                                 u'type': u'integer'},
                     u'opt-out': {u'type': u'boolean'},
                     u'skip-days': {u'items': {u'pattern': u'^[0-9]{4}-[0-9]{2}-[0-9]{2}',
                                               u'type': u'string'},
                                    u'type': u'array'},
                     u'skip-days-from': {u'additionalProperties': u'False',
                                         u'properties': {u'expr': {u'oneOf': [{u'type': u'integer'},
                                                                              {u'type': u'string'}]},
                                                         u'format': {u'enum': [u'csv',
                                                                               u'json',
                                                                               u'txt',
                                                                               u'csv2dict']},
                                                         u'url': {u'type': u'string'}},
                                         u'required': [u'url'],
                                         u'type': u'object'},
                     u'tag': {u'type': u'string'},
                     u'type': {u'enum': [u'offhour']},
                     u'weekends': {u'type': u'boolean'},
                     u'weekends-only': {u'type': u'boolean'}},
     u'required': [u'offhour', u'default_tz', u'type'],
     u'type': u'object'}

>On instance:
    {'default_tz': 'pt',
     'offhour': 20,
     'onhour': 8,
     'opt-out': True,
     'tag': 'downtime',
     'type': 'offhour',
     'weekends': False}

**Comment by thisisshi** [comment] 2018-01-08 14:32
Using onhours/offhours requires two separate policies, one to turn off the instance and one to turn it back on i.e.:

```yaml
- name: off-hour
  resource: ec2
  filters:
    - type: offhour
      tag: downtime
      default_tz: pt
      offhour: 20
      opt-out: True
      weekends: False
  actions:
    - stop

- name: on-hour
  resource: ec2
  filters:
    - type: onhour
      tag: downtime
      default_tz: pt
      onhour: 8
      opt-out: True
      weekends: False
  actions:
    - start
```

**Comment by mgarces** [comment] 2018-01-08 14:37
I can confirm what Sonny said; I ran into this exact problem, and ended up
splitting on/off policies into 2 lambdas.




Marco Garcês

*#sysadmin*
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDolvbEcFjSl8y3bBIX4qVr4QWa/Tx/BbJRedCfAUwsNWQHnvr7mchlGvm6IjXfqMtk35IxkQ9mI7FB1XJMdBWMlD5z4c/t3znf3hW/ZpsqaIDkiFn7I2LU1lUzgQbgVhNchq/Q3dhhp6vdNaLEVXjYOw6m8YJNg/Ymxlx1kqiA4wqIexdlH7NJjBz2qhBZOhwSnHwlVSQl+uhXef7n9He9mizJyaD71G4FzkvU7nxvyWcNYMYCf4RuwEKk2IkmbkMSYdtX5iZZ9sTOLYCLGqHFY0mAz9zfcXW3SG4brgtKgTm1MVtpvrH/EDsfjZGygRfv4Q21iCOMXwZVxswXULVZ
*marco at garces dot cc / mgarces at sysadnin dot pt*

**Comment by chaosdarky** [comment] 2018-01-08 16:52
Hi guys, 

Thanks for the quick response. May i ask how do you execute this on your environment? Is it through cron?

**Comment by thisisshi** [comment] 2018-01-08 19:01
Executing on a cron would work at your desired on/off-hour times

**Comment by chaosdarky** [comment] 2018-01-08 23:11
But if I will use cron, what’s the use of the onhours/offhours time use in the config?

**Comment by thisisshi** [comment] 2018-01-08 23:31
Custodian doesn’t execute continuously, the hour you specify in the policy will only execute the action when the time on the machine it’s executing on matches the time you specify. i.e. a policy specifying off hour at 8 will not do anything at 7 or 9 but will execute at 8. In this case, you can run the onhours/offhours policy in an hourly cron rather than at a specific hour which allows you to maintain a single cron for multiple actions (on/off) without two separate cron schedules. If you have developers in multiple timezones you can also maintain a single policy file with multiple on/off hour rules without worrying about the instances being turned on/off at the wrong time

**Comment by jhnlsn** [comment] 2018-01-10 04:30
Going to close this as it looks like the question was answered.  @chaosdarky if you have any other questions, don't hesitate to ask.  We are also available on gitter as well!

**Closed by jhnlsn** 2018-01-10 04:30 UTC
