### ISSUE TITLE
shield-enabled filter not working for Elastic IPs

### ISSUE THREAD

**Issue by dfengshi** [capitalone/cloud-custodian#2529] opened 2018-06-18 15:43 UTC
Hello,

A policy like this will return a list of all EIPs in the account instead of just the ones without shield protection enabled.

```
policies:
    - name: check-eip-shield
      resource: network-addr
      filters:
        - type: shield-enabled
          state: false
```

**Comment by dfengshi** [comment] 2018-06-21 18:32
@thisisshi The resource.json looks like this:

```

**Comment by thisisshi** [comment] 2018-06-21 18:46
this sounds similar to this https://github.com/capitalone/cloud-custodian/issues/2245

**Comment by dfengshi** [comment] 2018-06-21 18:54
@thisisshi yeah you're right, sounds similar. However, I only see the issue with EIPs. `c7n:ShieldProtected` for ALBs/ELBs/HostedZones/CloudFront seems to work fine.

**Comment by thisisshi** [comment] 2018-06-21 19:16
is it returning false for all resources or are some of them coming back as good?

**Comment by dfengshi** [comment] 2018-06-21 19:48
@thisisshi it's returning false for all EIPs

**Comment by thisisshi** [comment] 2018-06-21 19:55
ok, I think the issue is here: https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/shield.py#L62

model.type for elastic ip's in custodian is "network-addr" but "network-addr" doesn't appear in the elastic ip ARN, rather we should be looking for "eip-allocation".

**Comment by dfengshi** [comment] 2018-06-22 12:57
@thisisshi cool, thanks

however, with your PR, filtering for 
```
policies:
    - name: check-eip-shield
      resource: eip-allocation
      filters:
        - type: shield-enabled
          state: false
```

will give a validation error

**Comment by dfengshi** [comment] 2018-06-22 13:02
@thisisshi not sure if this is fixed, still getting `c7n:ShieldProtected": false` in the resource.json for EIPs that are shield protected

**Comment by thisisshi** [comment] 2018-06-22 13:22
Can you do a list_protections call and post the resourcearn for one of your elastic ips with account number and other sensitive data scrubbed?

**Comment by dfengshi** [comment] 2018-06-22 13:38
List protections returns something like this:

`"ResourceArn": "arn:aws:ec2:us-east-1:<accountid>:eip-allocation/eipalloc-61487d8e"`

**Comment by dfengshi** [comment] 2018-06-22 19:46
@thisisshi small fix that resolved it for me in this PR https://github.com/capitalone/cloud-custodian/pull/2556

**Comment by thisisshi** [comment] 2018-06-25 15:03
closing via #2556 and #2551

**Closed by thisisshi** 2018-06-25 15:03 UTC
Labels: area/actions, cloud/aws, kind/bug
