### ISSUE TITLE
db delete with final db snapshot identifier on replicas is not valid

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#417] opened 2016-08-30 14:13 UTC
ClientError: An error occurred (InvalidParameterCombination) when calling the
DeleteDBInstance operation: FinalDBSnapshotIdentifier can not be specified when
deleting a replica instance

**Comment by ewbankkit** [comment] 2016-09-13 12:09
This is a duplicate of the now resolved #436.

**Closed** 2016-10-08 09:05 UTC
Labels: area/actions, kind/bug, resource
