### ISSUE TITLE
c7n-org logging to cloudwatch?

### ISSUE THREAD

**Issue by getsec** [capitalone/cloud-custodian#3037] opened 2018-10-25 13:00 UTC
Hello, not sure if I've missed something in the documentation.

It doesn't look like c7n-org has any logging capabilities, would you be able to instruct me as to the best cause of action for this. I'd like to get the results of every account into the master account for log analysis / graphing.

Thanks.

**Comment by kapilt** [comment] 2018-10-25 15:31
dupe of #2645 lets move the discussion there, there's a pr in flight that improves the logging to blob/object storage location, but wrt to the direct cloud logging options, the biggest question is given a group how to format account and policy streams. in some contexts as well we've heard users prefer logs in the target account.

**Closed by kapilt** 2018-10-25 15:31 UTC
Labels: kind/duplicate
