### ISSUE TITLE
S3 bucket output_dir support for Lambda based policies

### ISSUE THREAD

**Issue by cliffpracht** [capitalone/cloud-custodian#2305] opened 2018-05-01 00:46 UTC
Hi there,

It appears that logging to S3 for the output_dir no longer works for Lambda-based Policies.  Here is a link to the event_handler where it appears the output_dir is overridden:
https://github.com/capitalone/cloud-custodian/blob/master/c7n/handler.py#L68-L81

Here is the example test policy I was using:
```
policies:
  - name: my-policy
    mode:
      role: arn:aws:iam::{account_id}:role/CloudCustodianLambdaRole
      type: periodic
      # This will trigger our rules at 15:20 UTC (11:20 EDT / 10:20 EST)
      schedule: 'cron(20 15 * * ? *)'
      timeout: 300
      execution-options:
        output_dir: s3://eis-c7n-logs/logs
    resource: asg
    filters:
      - "tag:TestTag": present
    actions:
      - type: rename-tag
        propagate: true
        source: TestTag
        dest: TestTag
```

And events to the Cloudwatch loggroup, where it is storing logs to dir:/tmp/c1495faf-51ad-4a9b-90dc-a8a5fb63096f/my-policy:

```
01:37:38
START RequestId: 1095034e-4c17-11e8-a94b-87d8950b5817 Version: $LATEST

01:37:38
[INFO] 2018-04-30T01:37:38.821Z ***** Processing event { "account": "*********", "region": "us-east-1", "detail": {}, "detail-type": "Scheduled Event", "source": "aws.events", "version": "0", "time": "2018-04-30T01:37:00Z", "debug": true, "id": "*********", "resources": [ "arn:aws:events:us-east-1:*****

01:37:39
[DEBUG] 2018-04-30T01:37:39.402Z 1095034e-4c17-11e8-a94b-87d8950b5817 Disabling cache

01:37:39
[DEBUG] 2018-04-30T01:37:39.403Z 1095034e-4c17-11e8-a94b-87d8950b5817 Storing output with <DirectoryOutput to dir:/tmp/c1495faf-51ad-4a9b-90dc-a8a5fb63096f/my-policy>

01:37:39
[DEBUG] 2018-04-30T01:37:39.403Z 1095034e-4c17-11e8-a94b-87d8950b5817 Running policy my-policy resource: asg region:us-east-1 c7n:0.8.28.2
```

Was this intentional or is this a bug?  Is S3 no longer supported for Lambda based deploys?

**Comment by kapilt** [comment] 2018-05-01 01:09
its a bug, the execution-options bit was a nice hack that enabled this but it lacked a test, we should fix and try to get a test into prevent any future regressions. it looks like in this case the generated temp overrides the execution option. it looks like we explicitly override on account id and output dir from execution options and we should instead only override the later if its not set.

**Comment by kapilt** [comment] 2018-05-01 18:32
i ended up having to touch something in handler for something unrelated so i went ahead and took care of this as well in #2299

**Comment by kapilt** [comment] 2018-05-02 12:38
fwiw the pr that fixes is merged.

**Closed by kapilt** 2018-05-02 12:38 UTC
Labels: kind/bug
