### ISSUE TITLE
Can we add copy-tag ability from EC2 snapshot action to the EBS snapshot action?

### ISSUE THREAD

**Issue by scoleri** [capitalone/cloud-custodian#2915] opened 2018-09-21 15:45 UTC
We have lots of unattached EBS volumes here and there.  We'd like to delete them but first do a snapshot which currently I'm doing using something like below.  However the new snapshots are completely unidentifiable.  If there is a way already to do this please help.

Thanks,

```
policies:
  - name: create-ebs-snapshots
    resource: ebs
    filters:
        - Attachments: []
        - "tag:CloudCustodianIgnore": absent
    actions:
       - type: snapshot
```

**Comment by thisisshi** [comment] 2018-09-21 19:19
@scoleri thanks for filing the issue, this is a duplicate of: https://github.com/capitalone/cloud-custodian/issues/2827, closing

**Closed by thisisshi** 2018-09-21 19:19 UTC

**Comment by sbalagopal** [comment] 2019-07-09 15:39
@thisisshi , #2497 does not provide a solution to the issue stated by @scoleri. Can you please re-open this issue as "ebs.actions.snapshot" does not have a way to copy tags from volumes to snapshot.

**Comment by sbalagopal** [comment] 2019-07-11 08:41
Can we have a static description at least to the function creating a snapshot to distinguish custodian created snapshots? something like below for a quick remedy? This will help me distinguish and clean up those that are created by the custodian.

"client.create_snapshot(VolumeId=volume,Description='Created by CloudCustodian...')"
